- name: installing nginx if redhat
  hosts: web
  become: yes
  tasks:
  - name: installing nginx in redhat using when keyword
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"
  
   - name: installing nginx in ubuntu using when keyword
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"