- name: loop
  hosts: local
  connection: local
  tasks:
  - name: print names using loops
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Parker
    - Levi
    - steve
    - ben