- name: loops
  hosts: local
  become: yes
  tasks:
  - name: installing packages in loops
    ansible.builtin.package:
      name: " {{ item }} "
      state: present
    loop:
    - maven
    - jenkins
    - docker
    - tree
    - git
    - maven
    - gcc


