- name: loops
  hosts: local
  become: yes
  tasks:
  - name: installing packages in loops
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'maven' , state: 'absent' }
    - { name: 'docker' , state: 'present' }
    - { name: 'tree' , state: 'absent' }
    - { name: 'gcc' , state: 'present' }
